version: "3"
services: 
  php:
    image: php_prod
    container_name: myphp1
    ports:
      - 9095:80
    depends_on:
      - db
      - phpmyadmin
    networks:
      - sumbridge

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myphpmyadmin1
    ports:
      - 8085:80
    depends_on:
      - db
    networks:
      - sumbridge

  db:
    image: mysql_prod
    container_name: mysqlnew1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /root/mysql_data:/var/lib/mysql
    networks:
      - sumbridge
    
networks:
  sumbridge:
    external: true
