####Create httpd image from centos
ARG VERSION=centos7
FROM centos:$VERSION
ENV var1=suma
RUN yum -y update && yum -y install httpd
WORKDIR /var/www/html
COPY index.html .
EXPOSE 80
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
